spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false
    open-in-view: false

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app/h2-db/db;AUTO_SERVER=TRUE;
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
api:
  url: https://api.tosspayments.com/v1/brandpay
  secretKey: secretKey

---
spring:
  profiles: local-oracle
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: testdb
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
